<?php

namespace Database\Seeders;

use App\Models\Officer;
use App\Models\User;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $officers = [
            // Batch 1
            [
                'channel_id' => 'UCmHRiGs6oI2XTr1VRwoKE9w',
                'handle' => '@EidoErtachta',
                'streamer_name' => "E'ido Ertachta",
                'officer_name' => "Ofc. E'ido Ertachta",
                'callsign' => '1-ADAM-01',
                'badge_number' => '#101',
                'department' => 'LSPD',
                'rank' => 'Officer',
                'patrol_zone' => 'Mission Row / Downtown',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=EidoErtachta',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCklUXUDzURMs8PW95PH1fIA',
                'handle' => '@babonkingrp',
                'streamer_name' => 'BABON KING',
                'officer_name' => 'Sgt. Babon King',
                'callsign' => '1-LINCOLN-02',
                'badge_number' => '#102',
                'department' => 'LSPD',
                'rank' => 'Sergeant',
                'patrol_zone' => 'Vinewood & Rockford Hills',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=babonkingrp',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCqnpXfBbZtSw_MDT5rqu7Hg',
                'handle' => '@tetewwwwwww',
                'streamer_name' => 'tetewww',
                'officer_name' => 'Ofc. Tetewww',
                'callsign' => '1-ADAM-14',
                'badge_number' => '#103',
                'department' => 'LSPD',
                'rank' => 'Officer',
                'patrol_zone' => 'South Central / Davis',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=tetewwwwwww',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UC1GfKPQjYhOnFMCbYw3a7tg',
                'handle' => '@danditguna',
                'streamer_name' => 'Betaa',
                'officer_name' => 'Deputy Betaa',
                'callsign' => '2-BAKER-05',
                'badge_number' => '#201',
                'department' => 'BCSO',
                'rank' => 'Deputy',
                'patrol_zone' => 'Sandy Shores & Senora',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=danditguna',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UC-_CykFgTDQkYMcru__olOA',
                'handle' => '@muchil',
                'streamer_name' => 'Muchil',
                'officer_name' => 'Ofc. Muchil',
                'callsign' => '1-UNION-08',
                'badge_number' => '#104',
                'department' => 'LSPD',
                'rank' => 'Senior Officer',
                'patrol_zone' => 'Vespucci & Del Perro',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=muchil',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UC9sob9rWyo4csnYizkjQ56Q',
                'handle' => '@sariluvu',
                'streamer_name' => 'Sari Luvu',
                'officer_name' => 'Ofc. Sari Luvu',
                'callsign' => '1-MARY-06',
                'badge_number' => '#105',
                'department' => 'TRAFFIC',
                'rank' => 'Officer',
                'patrol_zone' => 'Los Santos Freeway',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=sariluvu',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCv8qn5LoFjm56l26zTitllg',
                'handle' => '@Tyo-Karim',
                'streamer_name' => 'KARIMHERZA.GAMERS',
                'officer_name' => 'Trooper Karim Herza',
                'callsign' => '3-VICTOR-03',
                'badge_number' => '#301',
                'department' => 'SASP',
                'rank' => 'Master Trooper',
                'patrol_zone' => 'Route 68 & Paleto Hwy',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=TyoKarim',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCrKVaJk1MxCG8-ClRYLusLQ',
                'handle' => '@ucupmeletup',
                'streamer_name' => 'Ucup Meletup',
                'officer_name' => 'Deputy Ucup Meletup',
                'callsign' => '2-KING-04',
                'badge_number' => '#202',
                'department' => 'BCSO',
                'rank' => 'Senior Deputy',
                'patrol_zone' => 'Paleto Bay',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=ucupmeletup',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCHgXpMllK2rfhGMsdLSQffA',
                'handle' => '@SattEtrine',
                'streamer_name' => 'Satt Etrine',
                'officer_name' => 'Operator Satt Etrine',
                'callsign' => 'SWAT-02',
                'badge_number' => '#401',
                'department' => 'LSPD',
                'rank' => 'Tactical Operator',
                'patrol_zone' => 'Tactical Incident Sector',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=SattEtrine',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCgy-iitckvcugXd2ylwf2vw',
                'handle' => '@Bidosaputra',
                'streamer_name' => 'Bido Saputra',
                'officer_name' => 'Ofc. Bido Saputra',
                'callsign' => '1-ADAM-22',
                'badge_number' => '#106',
                'department' => 'LSPD',
                'rank' => 'Officer',
                'patrol_zone' => 'Downtown LS & Pillbox',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=Bidosaputra',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCB1JWtVC0Byiudb6klgM35w',
                'handle' => '@GraceTikaa_',
                'streamer_name' => 'Grace Tika',
                'officer_name' => 'TFO Grace Tika',
                'callsign' => 'AIR-1',
                'badge_number' => '#501',
                'department' => 'LSPD',
                'rank' => 'Tactical Flight Officer',
                'patrol_zone' => 'San Andreas Airspace',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=GraceTikaa',
                'is_active' => true,
            ],

            // Batch 2 (New Additions)
            [
                'channel_id' => 'UCVARRXQVAiAOTVN2RKUiAtw',
                'handle' => '@natxcunggg',
                'streamer_name' => 'cung',
                'officer_name' => 'Ofc. Cung',
                'callsign' => '1-ADAM-15',
                'badge_number' => '#107',
                'department' => 'LSPD',
                'rank' => 'Officer',
                'patrol_zone' => 'Vinewood Hills',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=natxcunggg',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UC6kKhwMKitwECm-yceRSYnQ',
                'handle' => '@stereoutype',
                'streamer_name' => 'Fiorella',
                'officer_name' => 'Deputy Fiorella',
                'callsign' => '2-BAKER-12',
                'badge_number' => '#203',
                'department' => 'BCSO',
                'rank' => 'Deputy',
                'patrol_zone' => 'Grand Senora Desert',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=stereoutype',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCbgePOujTd-ynwYjODxd2Xg',
                'handle' => '@lisolll',
                'streamer_name' => 'Lisol',
                'officer_name' => 'Ofc. Lisol',
                'callsign' => '1-UNION-11',
                'badge_number' => '#108',
                'department' => 'LSPD',
                'rank' => 'Officer',
                'patrol_zone' => 'Little Seoul & Koreatown',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=lisolll',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UC2FkTmahWYOTwxgrRz4ZyEQ',
                'handle' => '@SIIGMAALRP',
                'streamer_name' => 'KEMAL SIIGMAAL TAKAHASHI',
                'officer_name' => 'Trooper Kemal Takahashi',
                'callsign' => '3-VICTOR-07',
                'badge_number' => '#302',
                'department' => 'SASP',
                'rank' => 'Senior Trooper',
                'patrol_zone' => 'Senora Freeway',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=SIIGMAALRP',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UC22JUqgu_okJXWoIImqrfxA',
                'handle' => '@ZaperQuinn',
                'streamer_name' => 'Zaper Quinn',
                'officer_name' => 'Ofc. Zaper Quinn',
                'callsign' => '1-ADAM-25',
                'badge_number' => '#109',
                'department' => 'LSPD',
                'rank' => 'Senior Officer',
                'patrol_zone' => 'Del Perro & Boardwalk',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=ZaperQuinn',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCY3-jm1lYAF_cjCsexCuZ1g',
                'handle' => '@Cakrakoen',
                'streamer_name' => 'Cakra Koentjoro Ch.',
                'officer_name' => 'Sgt. Cakra Koentjoro',
                'callsign' => '1-LINCOLN-05',
                'badge_number' => '#110',
                'department' => 'LSPD',
                'rank' => 'Sergeant',
                'patrol_zone' => 'Mission Row District',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=Cakrakoen',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCLDuP_tOOAwPTNCwu8e5FUg',
                'handle' => '@ropeee',
                'streamer_name' => 'Ropeee',
                'officer_name' => 'Deputy Ropeee',
                'callsign' => '2-KING-09',
                'badge_number' => '#204',
                'department' => 'BCSO',
                'rank' => 'Deputy',
                'patrol_zone' => 'Grapeseed & Mt. Chiliad',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=ropeee',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCvSuNMN453Sx3RQnyW_tPjA',
                'handle' => '@verlon17',
                'streamer_name' => 'VERLON',
                'officer_name' => 'Operator Verlon',
                'callsign' => 'SWAT-05',
                'badge_number' => '#402',
                'department' => 'LSPD',
                'rank' => 'Tactical Operator',
                'patrol_zone' => 'Tactical Response Sector',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=verlon17',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UC-72zl_vKuI1BKX1aryZHiA',
                'handle' => '@Fckrest',
                'streamer_name' => 'Awan D Cartier',
                'officer_name' => 'Ofc. Awan D Cartier',
                'callsign' => '1-MARY-09',
                'badge_number' => '#111',
                'department' => 'LSPD',
                'rank' => 'Motor Patrol Officer',
                'patrol_zone' => 'Great Ocean Highway',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=Fckrest',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UC-UO2oav_qP7rYTqGbDizlg',
                'handle' => '@NippleLickerForJustice',
                'streamer_name' => 'NippleLickerForJustice',
                'officer_name' => 'Deputy NL For Justice',
                'callsign' => '2-BAKER-18',
                'badge_number' => '#205',
                'department' => 'BCSO',
                'rank' => 'Deputy',
                'patrol_zone' => 'Sandy Shores',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=NippleLickerForJustice',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UC4YhS2m2KW8755jVhI37VZw',
                'handle' => '@zeamaysspencer',
                'streamer_name' => 'Zea Mays Spencer',
                'officer_name' => 'TFO Zea Mays Spencer',
                'callsign' => 'AIR-2',
                'badge_number' => '#502',
                'department' => 'LSPD',
                'rank' => 'Tactical Flight Officer',
                'patrol_zone' => 'San Andreas Airspace',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=zeamaysspencer',
                'is_active' => true,
            ],

            // Batch 3 (Additional Units)
            [
                'channel_id' => 'UCgkd-1ry76YHxolHU6LK8zg',
                'handle' => '@praygaa_',
                'streamer_name' => 'r4yo',
                'officer_name' => 'Ofc. R4yo',
                'callsign' => '1-ADAM-28',
                'badge_number' => '#112',
                'department' => 'LSPD',
                'rank' => 'Officer',
                'patrol_zone' => 'Pillbox Hill & Legion Square',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=praygaa_',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCHVkH_sBgKngO81CgASP6mA',
                'handle' => '@aezlevi',
                'streamer_name' => 'Aez',
                'officer_name' => 'Deputy Aez Levi',
                'callsign' => '2-BAKER-22',
                'badge_number' => '#206',
                'department' => 'BCSO',
                'rank' => 'Deputy',
                'patrol_zone' => 'Harmony & Route 68',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=aezlevi',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCmiXhxAhmnjTp4__d60yPqw',
                'handle' => '@AldyyyJG',
                'streamer_name' => 'Aldyyy',
                'officer_name' => 'Ofc. Aldyyy',
                'callsign' => '1-UNION-16',
                'badge_number' => '#113',
                'department' => 'LSPD',
                'rank' => 'Officer',
                'patrol_zone' => 'Hawick & Alta',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=AldyyyJG',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCJ4CCMec5agzJGZfPt2T1dA',
                'handle' => '@aintlifeofgors',
                'streamer_name' => 'Gori',
                'officer_name' => 'Trooper Gori',
                'callsign' => '3-VICTOR-11',
                'badge_number' => '#303',
                'department' => 'SASP',
                'rank' => 'Trooper',
                'patrol_zone' => 'Chumash & Zancudo',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=aintlifeofgors',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCksWWuZQ3YRg6YNWrNZyNjg',
                'handle' => '@DopAldop',
                'streamer_name' => 'Aldop',
                'officer_name' => 'Operator Aldop',
                'callsign' => 'SWAT-08',
                'badge_number' => '#403',
                'department' => 'LSPD',
                'rank' => 'Tactical Operator',
                'patrol_zone' => 'High Risk Sector',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=DopAldop',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCOCK35EsCMwgGkG_ew9nINA',
                'handle' => '@dedeknjit',
                'streamer_name' => 'DEDEKNJIT',
                'officer_name' => 'Ofc. Dedeknjit',
                'callsign' => '1-MARY-14',
                'badge_number' => '#114',
                'department' => 'LSPD',
                'rank' => 'Traffic Officer',
                'patrol_zone' => 'La Puerta Freeway',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=dedeknjit',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCTsA4KomqohrQevPm4tevOA',
                'handle' => '@Jabdifatwaofficial',
                'streamer_name' => 'Jabdifatwa',
                'officer_name' => 'Deputy Jabdifatwa',
                'callsign' => '2-KING-15',
                'badge_number' => '#207',
                'department' => 'BCSO',
                'rank' => 'Senior Deputy',
                'patrol_zone' => 'Procopio Beach & Paleto',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=Jabdifatwaofficial',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCvViURTNa70v1hlrsvmSAQw',
                'handle' => '@madarahadian',
                'streamer_name' => 'Mada Rahadian',
                'officer_name' => 'Ofc. Mada Rahadian',
                'callsign' => '1-ADAM-33',
                'badge_number' => '#115',
                'department' => 'LSPD',
                'rank' => 'Officer',
                'patrol_zone' => 'Burton & Eclipse Blvd',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=madarahadian',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCI-zRKzXfimVkGKtZ5JyGWQ',
                'handle' => '@OnessXD',
                'streamer_name' => 'OnessXD',
                'officer_name' => 'Trooper OnessXD',
                'callsign' => '3-VICTOR-15',
                'badge_number' => '#304',
                'department' => 'SASP',
                'rank' => 'Master Trooper',
                'patrol_zone' => 'Los Santos County HWY',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=OnessXD',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCiZJHtuuN0bG4ubi5XcoLmg',
                'handle' => '@memoravelle',
                'streamer_name' => 'Velle',
                'officer_name' => 'Ofc. Velle',
                'callsign' => '1-LINCOLN-19',
                'badge_number' => '#116',
                'department' => 'LSPD',
                'rank' => 'Senior Officer',
                'patrol_zone' => 'Morningwood & Richman',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=memoravelle',
                'is_active' => true,
            ],
            [
                'channel_id' => 'UCnaiXdpEh0ppTbqYhQfqatQ',
                'handle' => '@Lyonablln',
                'streamer_name' => 'Lyona',
                'officer_name' => 'K9 Handler Lyona',
                'callsign' => 'K9-03',
                'badge_number' => '#601',
                'department' => 'BCSO',
                'rank' => 'K9 Unit Handler',
                'patrol_zone' => 'Metro & Port of LS',
                'avatar_url' => 'https://api.dicebear.com/7.x/bottts/svg?seed=Lyonablln',
                'is_active' => true,
            ],
        ];

        foreach ($officers as $officerData) {
            Officer::updateOrCreate(
                ['channel_id' => $officerData['channel_id']],
                $officerData
            );
        }

        // Default admin user
        User::updateOrCreate(
            ['email' => 'dispatch@imerp-police.local'],
            [
                'name' => 'Head Dispatcher',
                'password' => bcrypt('password'),
            ]
        );
    }
}
